#!/usr/bin/env python3
"""Vectorize the supplied logo (public/brand/logo-source.jpg) into crisp SVG
paths, one compound path per brand color, using potrace.

Outputs:
  src/brand/logoPaths.ts     path data used by the <BrandLogo> component
  public/brand/logo.svg      full-color logo (for reuse outside the video)

Requires: potrace (apt install potrace), pillow, numpy.
If you get an official vector logo, replace this with that file's paths.
"""
import json, re, subprocess, tempfile
from pathlib import Path
import numpy as np
from PIL import Image, ImageFilter

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "public/brand/logo-source.jpg"
S = 6  # upscale factor before tracing -> smoother curves
NAVY, GREEN = "#2D2F7A", "#63AF45"  # sampled from the logo (median of saturated pixels)

im = Image.open(SRC).convert("RGB")
W, H = im.size
big = im.resize((W * S, H * S), Image.LANCZOS).filter(ImageFilter.GaussianBlur(S * 0.45))
a = np.asarray(big).astype(float)
R, G, B = a[..., 0], a[..., 1], a[..., 2]
ink = a.mean(2) < 190
# classify by hue so anti-aliased navy edges don't leak into the green layer
green = ink & (G > R + 25) & (G > B + 15)
navy = ink & ~green & (B > G + 10)

layers = {}
with tempfile.TemporaryDirectory() as tmp:
    for name, mask in (("navy", navy), ("green", green)):
        pbm, svg = Path(tmp) / f"{name}.pbm", Path(tmp) / f"{name}.svg"
        Image.fromarray(np.where(mask, 0, 255).astype(np.uint8)).save(pbm)
        subprocess.check_call(["potrace", str(pbm), "-s", "-o", str(svg), "--turdsize", "60",
                               "--alphamax", "1.1", "--opttolerance", "0.3", "--flat"])
        src = svg.read_text()
        g = re.search(r'<g transform="([^"]+)"[^>]*>(.*?)</g>', src, re.S)
        layers[name] = {"transform": f"scale({1 / S:.6f}) {g.group(1)}",
                        "d": " ".join(re.findall(r'<path d="([^"]+)"', g.group(2)))}

ts = (
    "// Generated by scripts/trace_logo.py from public/brand/logo-source.jpg. Do not edit.\n"
    f"export const LOGO_VIEWBOX = {{ width: {W}, height: {H} }};\n"
    f"export const LOGO_COLORS = {{ navy: \"{NAVY}\", green: \"{GREEN}\" }};\n"
    f"export const LOGO_LAYERS = {json.dumps(layers, indent=2)} as const;\n"
)
(ROOT / "src/brand/logoPaths.ts").write_text(ts)
svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}">'
       + "".join(f'<path transform="{l["transform"]}" fill="{c}" d="{l["d"]}"/>'
                 for l, c in ((layers["navy"], NAVY), (layers["green"], GREEN)))
       + "</svg>")
(ROOT / "public/brand/logo.svg").write_text(svg)
print("wrote src/brand/logoPaths.ts and public/brand/logo.svg")
